FROM osgeo/gdal:ubuntu-small-latest-amd64
SHELL ["/bin/bash", "-c"]
RUN uname -a
RUN apt-get update && \
apt-get upgrade -y && \
apt-get install -y --no-install-recommends \
wget \
git \
unzip \
zip \
nano \
vim \
locate \
php7.4 \
python3-numpy \
python3-joblib \
python3-skimage \
sqlite3 \
php7.4-sqlite3 \
php-mbstring \
default-jre-headless \
imagemagick \
libjpeg62 \
libglu1-mesa \
libgtk2.0-0 \
libidn11 \
libsm6 \
x11-apps && \
rm -rf /var/lib/apt/lists/*
ENV imodfile='imod_4.9.12_RHEL7-64_CUDA8.0.sh'
RUN mkdir /opt/src
WORKDIR /opt/src
RUN wget http://bio3d.colorado.edu/imod/AMD64-RHEL5/$imodfile
RUN chmod a+x $imodfile
#RUN ./$imodfile -yes
RUN ./$imodfile -extract
WORKDIR /opt/src/IMODtempDir
RUN /bin/sed -i '/if bit3264 == 4:/c\#' installIMOD
RUN /bin/sed -i "/libdir = '\/usr\/lib64'/c\#" installIMOD
RUN ./installIMOD
WORKDIR /opt/src
RUN rm -rf /opt/src/IMODtempDir
RUN rm -rf /opt/src/$imodfile
RUN /bin/sh /etc/profile.d/IMOD-linux.sh
RUN cp /etc/ImageMagick-6/policy.xml /etc/ImageMagick-6/policy.bac
RUN /bin/sed -i '/<policy /c\' /etc/ImageMagick-6/policy.xml
RUN /bin/sed -i '/;extension=sqlite3/s/;//g' /usr/lib/php/7.4/php.ini-*
RUN /bin/sed -i '/^;sqlite3.extension_dir.*/c\sqlite3.extension_dir = /usr/lib/php/20190902' /usr/lib/php/7.4/php.ini-*
ENV PATH="/usr/local/IMOD/bin/realbin/:$PATH"
ENV IMOD_QTLIBDIR="/usr/local/IMOD/qtlib"
ENV LD_LIBRARY_PATH="/usr/lib/x86_64-linux-gnu:/usr/local/IMOD/lib:$IMOD_QTLIBDIR:$LD_LIBRARY_PATH"
ENV IMOD_PLUGIN_DIR="/usr/local/IMOD/lib/imodplug"
RUN git clone https://github.com/CRBS/Image_Viewer_Data_Converter.git
WORKDIR /opt/src/Image_Viewer_Data_Converter
VOLUME /opt/src/Image_Viewer_Data_Converter/cil
VOLUME /opt/src/Image_Viewer_Data_Converter/ccdb
VOLUME /opt/src/Image_Viewer_Data_Converter/fast
VOLUME /opt/src/Image_Viewer_Data_Converter/data
RUN chmod +x *.php
RUN chmod +x *.py
CMD exec /bin/bash -c "trap : TERM INT; sleep infinity & wait"

